packages:
  - docs
  - 'packages/*'

catalog:
  '@clack/prompts': ^0.10.0
  '@deviltea/eslint-config': 4.0.0
  '@deviltea/tsconfig': 0.0.7
  '@shikijs/vitepress-twoslash': ^3.0.0
  '@types/node': ^22.13.5
  '@vitest/coverage-v8': ^3.0.7
  bumpp: ^10.0.3
  eslint: ^9.21.0
  lint-staged: ^15.4.3
  pathe: ^2.0.3
  pkg-size: ^2.4.0
  publint: ^0.3.7
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  tsx: ^4.19.3
  typescript: ^5.7.3
  unbuild: ^3.5.0
  vite: ^6.2.0
  vitepress: ^2.0.0-alpha.3
  vitepress-plugin-group-icons: ^1.3.6
  vitest: ^3.0.7
  vue: ^3.5.16
  vue-tsc: ^2.2.4
  zx: ^8.3.2
